//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>

pub(crate) mod r#dex;
pub(crate) mod r#route;
pub(crate) mod r#swap_event;

pub use self::{r#dex::*, r#route::*, r#swap_event::*};
