//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>

use solana_pubkey::{pubkey, Pubkey};

/// `router` program ID.
pub const ROUTER_ID: Pubkey = pubkey!("H3SocRxYoShPJ9z184k9tomq2GPViDKEghyYEr1SGrXE");
